export const DAO_ANH_ELEMENT_TYPES = {
  ALL: { id: 'all', name: 'Tất Cả', icon: '🌌' },
  HON_DON: { id: 'hon_don', name: 'Hỗn Độn & Khởi Nguyên', icon: '💥' },
  MA_DAO: { id: 'ma_dao', name: 'Ma Đạo & Hắc Ám', icon: '🌑' },
  LOI_DINH: { id: 'loi_dinh', name: 'Lôi Đình & Kiếp Phạt', icon: '⚡' },
  LUAN_HOI: { id: 'luan_hoi', name: 'Luân Hồi & Túc Mệnh', icon: '☯️' },
  THAI_DUONG: { id: 'thai_duong', name: 'Thái Dương & Chân Hỏa', icon: '☀️' },
  THOI_KHONG: { id: 'thoi_khong', name: 'Thời Không & Tinh Thần', icon: '⏳' },
  TAO_HOA: { id: 'tao_hoa', name: 'Tạo Hóa & Sinh Mệnh', icon: '🌿' },
  KIEM_DAO: { id: 'kiem_dao', name: 'Kiếm Đạo & Sát Phạt', icon: '⚔️' },
  THAN_THE: { id: 'than_the', name: 'Thần Thể & Vô Địch', icon: '👑' },
};

export const DAO_ANH_LIST = [
  // =========================================================================
  // I. 18 ĐẠO ANH HÓA SINH TỪ MỆNH ĐĂNG THẦN PHẨM
  // =========================================================================
  {
    id: 'da_nguyen_thuy_thien_ma',
    sourceType: 'lamp',
    sourceId: 'nguyen_thuy_thien_ma',
    name: 'Nguyên Thủy Thiên Ma Đạo Anh',
    title: 'Vạn Ma Tối Cao Chi Tổ',
    category: 'ma_dao',
    tier: 'than_pham',
    image: '/images/dao_anh/nguyen_thuy_thien_ma.png',
    evolutionImages: [
      '/images/dao_anh/nguyen_thuy_thien_ma.png',
      '/images/dao_anh/nguyen_thuy_thien_ma_k2.png',
      '/images/dao_anh/nguyen_thuy_thien_ma_k3.png',
      '/images/dao_anh/nguyen_thuy_thien_ma_k4.png',
      '/images/dao_anh/nguyen_thuy_thien_ma_k5.png',
    ],
    primaryColor: '#a855f7',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.75)',
    bgGradient: 'radial-gradient(circle, rgba(168,85,247,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'dark_violet_obsidian',
    eyeStyle: 'demon_red_veins',
    foreheadMark: 'ancient_demon_seal',
    ribbonStyle: 'dark_miasma_flames',
    coreStyle: 'black_lotus_void',
    poem: 'Nguyên thủy thiên ma, thống ngự vạn ma.',
    desc: 'Đạo Anh sinh ra từ Nguyên Thủy Thiên Ma Đăng. Thân thể ngưng tụ từ ma diễm sơ khai và tử khí u minh, đôi mắt huyết đồng nhìn thấu hư vọng ma chướng tam giới.',
    skillName: 'Thiên Ma Vạn Giới Thôn Phệ',
    skillDesc: 'Tăng 60% Sát Thương Ma Đạo, mỗi đòn đánh hút 15% linh lực chuyển hóa thành Thiên Mệnh.',
    tribulationForm: 'Cửu U Thiên Ma Hoàng Kim Thể',
  },
  {
    id: 'da_hon_don_so_khai',
    sourceType: 'lamp',
    sourceId: 'hon_don_so_khai',
    name: 'Hỗn Độn Sơ Khai Đạo Anh',
    title: 'Vạn Đạo Chi Khởi Nguyên',
    category: 'hon_don',
    tier: 'than_pham',
    image: '/images/dao_anh/hon_don_so_khai.png',
    evolutionImages: [
      '/images/dao_anh/hon_don_so_khai.png',
      '/images/dao_anh/hon_don_so_khai_k2.png',
      '/images/dao_anh/hon_don_so_khai_k3.png',
      '/images/dao_anh/hon_don_so_khai_k4.png',
      '/images/dao_anh/hon_don_so_khai_k5.png',
    ],
    primaryColor: '#c084fc',
    secondaryColor: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 0.75)',
    bgGradient: 'radial-gradient(circle, rgba(192,132,252,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'cosmic_nebula_violet',
    eyeStyle: 'cosmic_starlight_gold',
    foreheadMark: 'chaos_primordial_sigil',
    ribbonStyle: 'starlight_dust_wisps',
    coreStyle: 'galaxy_spiral_singularity',
    poem: 'Hỗn độn vị phân, nhất điểm linh quang.',
    desc: 'Đạo Anh ngưng kết khi thiên địa còn là một mảnh hỗn mang sơ khai. Lồng ngực xoáy động một vòng xoáy tinh hà chứa đựng vạn pháp nguyên thủy.',
    skillName: 'Hỗn Độn Vạn Pháp Quy Tông',
    skillDesc: 'Miễn nhiễm 40% sát thương ngũ hành, tăng 50% hiệu suất hấp thu EXP Đạo Cung.',
    tribulationForm: 'Hỗn Độn Bất Diệt Thánh Thai',
  },
  {
    id: 'da_hong_mong_bat_diet',
    sourceType: 'lamp',
    sourceId: 'hong_mong_bat_diet',
    name: 'Hồng Mông Bất Diệt Đạo Anh',
    title: 'Tiên Thiên Bất Hủ Chi Linh',
    category: 'hon_don',
    tier: 'than_pham',
    image: '/images/dao_anh/hong_mong_bat_diet.png',
    evolutionImages: [
      '/images/dao_anh/hong_mong_bat_diet.png',
      '/images/dao_anh/hong_mong_bat_diet_k2.png',
      '/images/dao_anh/hong_mong_bat_diet_k3.png',
      '/images/dao_anh/hong_mong_bat_diet_k4.png',
      '/images/dao_anh/hong_mong_bat_diet_k5.png',
    ],
    primaryColor: '#f472b6',
    secondaryColor: '#c084fc',
    glowColor: 'rgba(244, 114, 182, 0.75)',
    bgGradient: 'radial-gradient(circle, rgba(244,114,182,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'purple_lotus_crystal',
    eyeStyle: 'transcendent_amethyst',
    foreheadMark: 'hong_mong_lotus_mark',
    ribbonStyle: 'purple_mist_petals',
    coreStyle: 'immortal_purple_core',
    poem: 'Hồng mông tử khí, vĩnh hằng bất hủ.',
    desc: 'Đạo Anh hấp thu Hồng Mông Tử Khí viễn cổ, thân như ngọc tím lưu ly bất hoại trước vạn kiếp lôi phạt.',
    skillName: 'Hồng Mông Tử Khí Hộ Thể',
    skillDesc: 'Tạo lớp giáp tử khí hấp thu 100% sát thương chí mạng 1 lần mỗi lần độ kiếp.',
    tribulationForm: 'Hồng Mông Vạn Kiếp Kim Cương Thân',
  },
  {
    id: 'da_cuu_chuyen_luan_hoi',
    sourceType: 'lamp',
    sourceId: 'cuu_chuyen_luan_hoi',
    name: 'Cửu Chuyển Luân Hồi Đạo Anh',
    title: 'Lục Đạo Sinh Tử Chưởng Khống',
    category: 'luan_hoi',
    tier: 'than_pham',
    image: '/images/dao_anh/cuu_chuyen_luan_hoi.png',
    evolutionImages: [
      '/images/dao_anh/cuu_chuyen_luan_hoi.png',
      '/images/dao_anh/cuu_chuyen_luan_hoi_k2.png',
      '/images/dao_anh/cuu_chuyen_luan_hoi_k3.png',
      '/images/dao_anh/cuu_chuyen_luan_hoi_k4.png',
      '/images/dao_anh/cuu_chuyen_luan_hoi_k5.png',
    ],
    primaryColor: '#38bdf8',
    secondaryColor: '#e2e8f0',
    glowColor: 'rgba(56, 189, 248, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(56,189,248,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'yin_yang_dual_crystal',
    eyeStyle: 'reincarnation_silver_pupil',
    foreheadMark: 'taiji_yin_yang_mark',
    ribbonStyle: 'six_paths_light_stream',
    coreStyle: 'six_paths_chakra_wheel',
    poem: 'Cửu chuyển luân hồi, nghịch chuyển sinh tử.',
    desc: 'Đạo Anh chưởng quản sáu nẻo luân hồi, có thể nghịch chuyển nhân quả sinh tử, đưa tu vi vượt qua gông cùm kiếp nạn.',
    skillName: 'Lục Đạo Nghịch Chuyển',
    skillDesc: 'Tăng 100% tỷ lệ vượt Lôi Kiếp Đạo Anh an toàn, tự động hồi phục 50% Thiên Mệnh khi chạm đáy.',
    tribulationForm: 'Lục Đạo Luân Hồi Chí Tôn Thân',
  },
  {
    id: 'da_thuong_thuong_loi_kiep',
    sourceType: 'lamp',
    sourceId: 'thuong_thuong_loi_kiep',
    name: 'Thượng Thương Lôi Kiếp Đạo Anh',
    title: 'Thiên Phạt Cửu Tiêu Lôi Đế',
    category: 'loi_dinh',
    tier: 'than_pham',
    image: '/images/dao_anh/thuong_thuong_loi_kiep.png',
    evolutionImages: [
      '/images/dao_anh/thuong_thuong_loi_kiep.png',
      '/images/dao_anh/thuong_thuong_loi_kiep_k2.png',
      '/images/dao_anh/thuong_thuong_loi_kiep_k3.png',
      '/images/dao_anh/thuong_thuong_loi_kiep_k4.png',
      '/images/dao_anh/thuong_thuong_loi_kiep_k5.png',
    ],
    primaryColor: '#60a5fa',
    secondaryColor: '#facc15',
    glowColor: 'rgba(96, 165, 250, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(96,165,250,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'electric_azure_plasma',
    eyeStyle: 'lightning_sparkling_blue',
    foreheadMark: 'divine_thunder_crest',
    ribbonStyle: 'crackling_lightning_arcs',
    coreStyle: 'thunder_singularity_pool',
    poem: 'Thượng thương lôi kiếp, thần phạt giáng lâm.',
    desc: 'Đạo Anh hình thành từ sấm sét chín tầng trời của Thượng Thương. Khắp thân thể lưu ly tràn ngập điện quang lam biếc chấn nhiếp ma quỷ.',
    skillName: 'Thượng Thương Thần Phạt Lôi',
    skillDesc: 'Tăng 75% Bạo Kích Pháp Thuật, phóng sét giáng đòn x3 uy lực khi độ kiếp.',
    tribulationForm: 'Cửu Tiêu Diệt Thế Lôi Thần Thể',
  },
  {
    id: 'da_sang_the_ban_nguyen',
    sourceType: 'lamp',
    sourceId: 'sang_the_ban_nguyen',
    name: 'Sáng Thế Bản Nguyên Đạo Anh',
    title: 'Khai Thiên Diễn Hóa Thánh Tôn',
    category: 'hon_don',
    tier: 'than_pham',
    image: '/images/dao_anh/sang_the_ban_nguyen.png',
    evolutionImages: [
      '/images/dao_anh/sang_the_ban_nguyen.png',
      '/images/dao_anh/sang_the_ban_nguyen_k2.png',
      '/images/dao_anh/sang_the_ban_nguyen_k3.png',
      '/images/dao_anh/sang_the_ban_nguyen_k4.png',
      '/images/dao_anh/sang_the_ban_nguyen_k5.png',
    ],
    primaryColor: '#fbbf24',
    secondaryColor: '#f59e0b',
    glowColor: 'rgba(251, 191, 36, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(251,191,36,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'radiant_pure_gold',
    eyeStyle: 'genesis_starlight_gold',
    foreheadMark: 'genesis_flame_crest',
    ribbonStyle: 'genesis_celestial_ribbons',
    coreStyle: 'genesis_tesseract_matrix',
    poem: 'Sáng thế bản nguyên, diễn hóa vạn giới.',
    desc: 'Đạo Anh chưởng khống Ma Phương Sáng Thế sơ khai, mở ra quy tắc không gian và các dải ngân hà, sinh sôi linh khí vô cùng tận nuôi dưỡng đan điền.',
    skillName: 'Sáng Thế Vạn Vật Hóa Sinh',
    skillDesc: 'Tự động hồi 100 Điểm EXP mỗi giây, tăng 50% tổng sức chứa Thiên Cung.',
    tribulationForm: 'Sáng Thế Khai Thiên Vĩnh Hằng Thân',
  },
  {
    id: 'da_van_menh_hu_vo',
    sourceType: 'lamp',
    sourceId: 'van_menh_hu_vo',
    name: 'Vận Mệnh Hư Vô Đạo Anh',
    title: 'Tịch Diệt Hư Không Đạo Tôn',
    category: 'thoi_khong',
    tier: 'than_pham',
    image: '/images/dao_anh/van_menh_hu_vo.png',
    evolutionImages: [
      '/images/dao_anh/van_menh_hu_vo.png',
      '/images/dao_anh/van_menh_hu_vo_k2.png',
      '/images/dao_anh/van_menh_hu_vo_k3.png',
      '/images/dao_anh/van_menh_hu_vo_k4.png',
      '/images/dao_anh/van_menh_hu_vo_k5.png',
    ],
    primaryColor: '#94a3b8',
    secondaryColor: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.7)',
    bgGradient: 'radial-gradient(circle, rgba(148,163,184,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'ghostly_void_silver',
    eyeStyle: 'void_black_hole_eyes',
    foreheadMark: 'destiny_astrolabe_mark',
    ribbonStyle: 'spacetime_distortion_veil',
    coreStyle: 'black_hole_event_horizon',
    poem: 'Vận mệnh hư vô, chư thiên quy tịch.',
    desc: 'Đạo Anh trong suốt tựa sương khói bạc, mang sức mạnh làm tan biến mọi đạo pháp công kích rơi vào cõi hư vô tịch diệt.',
    skillName: 'Hư Vô Tịch Diệt Giới',
    skillDesc: 'Hóa giải 50% toàn bộ sát thương gánh chịu, triệt tiêu mọi trạng thái suy yếu.',
    tribulationForm: 'Vận Mệnh Vô Tướng Chân Thân',
  },
  {
    id: 'da_tuc_menh_nhan_qua',
    sourceType: 'lamp',
    sourceId: 'tuc_menh_nhan_qua',
    name: 'Túc Mệnh Nhân Quả Đạo Anh',
    title: 'Thiên Mệnh Nhân Duyên Chi Chủ',
    category: 'luan_hoi',
    tier: 'than_pham',
    image: '/images/dao_anh/tuc_menh_nhan_qua.png',
    evolutionImages: [
      '/images/dao_anh/tuc_menh_nhan_qua.png',
      '/images/dao_anh/tuc_menh_nhan_qua_k2.png',
      '/images/dao_anh/tuc_menh_nhan_qua_k3.png',
      '/images/dao_anh/tuc_menh_nhan_qua_k4.png',
      '/images/dao_anh/tuc_menh_nhan_qua_k5.png',
    ],
    primaryColor: '#f43f5e',
    secondaryColor: '#fbbf24',
    glowColor: 'rgba(244, 63, 94, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(244,63,94,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'crimson_coral_glass',
    eyeStyle: 'crimson_destiny_glance',
    foreheadMark: 'karma_infinity_knot',
    ribbonStyle: 'red_thread_destiny_ribbons',
    coreStyle: 'karma_core_pearl',
    poem: 'Túc mệnh nhân quả, thiên đạo luân hồi.',
    desc: 'Đạo Anh kết nối bởi hàng ức vạn sợi tơ nhân quả vô hình, nhìn thấy trước tương lai và cắt đứt số mệnh suy thoái.',
    skillName: 'Túc Mệnh Đoạt Thiên Chỉ',
    skillDesc: 'Khiến kẻ địch tự gánh chịu 40% sát thương do chính chúng gây ra phản hồi nhân quả.',
    tribulationForm: 'Đại Thiên Túc Mệnh Thần Thai',
  },
  {
    id: 'da_thai_co_than_long',
    sourceType: 'lamp',
    sourceId: 'thai_co_than_long',
    name: 'Thái Cổ Thần Long Đạo Anh',
    title: 'Vạn Thú Chi Tổ · Chân Long',
    category: 'than_the',
    tier: 'than_pham',
    image: '/images/dao_anh/thai_co_than_long.png',
    evolutionImages: [
      '/images/dao_anh/thai_co_than_long.png',
      '/images/dao_anh/thai_co_than_long_k2.png',
      '/images/dao_anh/thai_co_than_long_k3.png',
      '/images/dao_anh/thai_co_than_long_k4.png',
      '/images/dao_anh/thai_co_than_long_k5.png',
    ],
    primaryColor: '#f59e0b',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(245, 158, 11, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(245,158,11,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'golden_dragon_scale_amber',
    eyeStyle: 'dragon_slit_ruby',
    foreheadMark: 'dragon_horns_crest',
    ribbonStyle: 'dragon_qi_golden_clouds',
    coreStyle: 'primordial_dragon_pearl',
    poem: 'Tổ long rít gào, uy chấn bát hoang.',
    desc: 'Đạo Anh mang hình hài tiểu long thai uy nghi, đầu nhú đôi sừng rồng hoàng kim, bao bọc bởi tường vân vạn trượng.',
    skillName: 'Tổ Long Hống Chấn Bát Hoang',
    skillDesc: 'Gây choáng ngợp và giảm 50% phòng ngự toàn bộ đối thủ trong tầm ảnh hưởng.',
    tribulationForm: 'Thái Cổ Ngũ Trảo Kim Long Thân',
  },
  {
    id: 'da_khoi_nguyen_thoi_khong',
    sourceType: 'lamp',
    sourceId: 'khoi_nguyen_thoi_khong',
    name: 'Khởi Nguyên Thời Không Đạo Anh',
    title: 'Tuế Nguyệt Trường Hà Thần Tôn',
    category: 'thoi_khong',
    tier: 'than_pham',
    image: '/images/dao_anh/khoi_nguyen_thoi_khong.png',
    evolutionImages: [
      '/images/dao_anh/khoi_nguyen_thoi_khong.png',
      '/images/dao_anh/khoi_nguyen_thoi_khong_k2.png',
      '/images/dao_anh/khoi_nguyen_thoi_khong_k3.png',
      '/images/dao_anh/khoi_nguyen_thoi_khong_k4.png',
      '/images/dao_anh/khoi_nguyen_thoi_khong_k5.png',
    ],
    primaryColor: '#818cf8',
    secondaryColor: '#38bdf8',
    glowColor: 'rgba(129, 140, 248, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(129,140,248,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'chronos_cyan_indigo',
    eyeStyle: 'hourglass_sapphire',
    foreheadMark: 'chronos_time_dial',
    ribbonStyle: 'time_stream_orbital_rings',
    coreStyle: 'timeless_sand_matrix',
    poem: 'Khởi nguyên thời không, ngạo thị tuế nguyệt.',
    desc: 'Đạo Anh đạp trên dòng sông thời gian, có thể làm chậm dòng chảy tuế nguyệt xung quanh và tăng tốc độ ngộ đạo gấp bội.',
    skillName: 'Thời Không Đình Trệ Vực',
    skillDesc: 'Tăng 100% Tốc Độ Tu Luyện, giảm 50% thời gian chờ độ kiếp của toàn bộ Đạo Anh.',
    tribulationForm: 'Tuế Nguyệt Vĩnh Hằng Bất Lão Thân',
  },
  {
    id: 'da_van_gioi_quy_nhat',
    sourceType: 'lamp',
    sourceId: 'van_gioi_quy_nhat',
    name: 'Vạn Giới Quy Nhất Đạo Anh',
    title: 'Thập Phương Hợp Nhất Thánh Hoàng',
    category: 'hon_don',
    tier: 'than_pham',
    image: '/images/dao_anh/van_gioi_quy_nhat.png',
    evolutionImages: [
      '/images/dao_anh/van_gioi_quy_nhat.png',
      '/images/dao_anh/van_gioi_quy_nhat_k2.png',
      '/images/dao_anh/van_gioi_quy_nhat_k3.png',
      '/images/dao_anh/van_gioi_quy_nhat_k4.png',
      '/images/dao_anh/van_gioi_quy_nhat_k5.png',
    ],
    primaryColor: '#e879f9',
    secondaryColor: '#38bdf8',
    glowColor: 'rgba(232, 121, 249, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(232,121,249,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'prism_rainbow_crystal',
    eyeStyle: 'omni_rainbow_gaze',
    foreheadMark: 'omni_world_trigram',
    ribbonStyle: 'aurora_borealis_flow',
    coreStyle: 'unification_crystal_sphere',
    poem: 'Vạn giới quy nhất, vạn pháp quy tông.',
    desc: 'Đạo Anh dung hợp tinh hoa của 10 phương thế giới, biến mọi luồng năng lượng xung đột thành thể đồng nhất hoàn mỹ.',
    skillName: 'Vạn Đạo Đồng Lưu Đại Pháp',
    skillDesc: 'Tăng 45% Sức Mạnh Chiến Đấu tổng thể cho toàn bộ 13 Thiên Cung Đạo Anh.',
    tribulationForm: 'Vạn Giới Đồng Huy Thánh Thể',
  },
  {
    id: 'da_toi_cao_thien_menh',
    sourceType: 'lamp',
    sourceId: 'toi_cao_thien_menh',
    name: 'Tối Cao Thiên Mệnh Đạo Anh',
    title: 'Thiên Đạo Hoàng Cực Chi Tôn',
    category: 'than_the',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/toi_cao_thien_menh.png',
      '/images/dao_anh/toi_cao_thien_menh_k2.png',
      '/images/dao_anh/toi_cao_thien_menh_k3.png',
      '/images/dao_anh/toi_cao_thien_menh_k4.png',
      '/images/dao_anh/toi_cao_thien_menh_k5.png',
    ],
image: '/images/dao_anh/toi_cao_thien_menh.png',
    primaryColor: '#fde047',
    secondaryColor: '#b45309',
    glowColor: 'rgba(253, 224, 71, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(253,224,71,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'imperial_sovereign_gold',
    eyeStyle: 'emperor_majestic_gold',
    foreheadMark: 'imperial_crown_seal',
    ribbonStyle: 'imperial_dragon_banners',
    coreStyle: 'imperial_jade_seal_core',
    poem: 'Thiên mệnh sở quy, vạn kiếp bất hủ.',
    desc: 'Đạo Anh sinh ra mang hoàng uy thiên mệnh tối cao, đầu đội đế miện hoàng kim, lời nói ra là pháp tắc thiên địa.',
    skillName: 'Thiên Mệnh Hoàng Cực Trấn',
    skillDesc: 'Tăng 80% Lực Trấn Áp Thiên Cung, bảo vệ Đạo Cơ vĩnh viễn không bao giờ rạn nứt.',
    tribulationForm: 'Cửu Ngũ Chí Tôn Thiên Đế Thể',
  },
  {
    id: 'da_cuu_khieu_linh_lung',
    sourceType: 'lamp',
    sourceId: 'cuu_khieu_linh_lung',
    name: 'Cửu Khiếu Linh Lung Đạo Anh',
    title: 'Thất Sắc Thông Thiên Thần Anh',
    category: 'tao_hoa',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/cuu_khieu_linh_lung.png',
      '/images/dao_anh/cuu_khieu_linh_lung_k2.png',
      '/images/dao_anh/cuu_khieu_linh_lung_k3.png',
      '/images/dao_anh/cuu_khieu_linh_lung_k4.png',
      '/images/dao_anh/cuu_khieu_linh_lung_k5.png',
    ],
image: '/images/dao_anh/cuu_khieu_linh_lung.png',
    primaryColor: '#2dd4bf',
    secondaryColor: '#f472b6',
    glowColor: 'rgba(45, 212, 191, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(45,212,191,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'flawless_diamond_prismatic',
    eyeStyle: 'seven_color_sparkle',
    foreheadMark: 'nine_aperture_gem_crest',
    ribbonStyle: 'prismatic_diamond_light',
    coreStyle: 'nine_orifices_heart',
    poem: 'Cửu khiếu linh lung, đắc ngộ đại đạo.',
    desc: 'Đạo Anh trong vắt như kim cương thất sắc với 9 đại khiếu huyệt tỏa ánh sáng rực rỡ, nhìn thấu điểm yếu của vạn pháp.',
    skillName: 'Cửu Khiếu Thông Thiên Nhãn',
    skillDesc: 'Phát hiện ngay lập tức 100% điểm yếu của thiên kiếp, giảm 40% sát thương lôi kiếp.',
    tribulationForm: 'Linh Lung Thất Sắc Bảo Quang Thân',
  },
  {
    id: 'da_thien_dao_chi_ton',
    sourceType: 'lamp',
    sourceId: 'thien_dao_chi_ton',
    name: 'Thiên Đạo Chí Tôn Đạo Anh',
    title: 'Chấp Chưởng Thiên Quy Thần Tôn',
    category: 'than_the',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/thien_dao_chi_ton.png',
      '/images/dao_anh/thien_dao_chi_ton_k2.png',
      '/images/dao_anh/thien_dao_chi_ton_k3.png',
      '/images/dao_anh/thien_dao_chi_ton_k4.png',
      '/images/dao_anh/thien_dao_chi_ton_k5.png',
    ],
image: '/images/dao_anh/thien_dao_chi_ton.png',
    primaryColor: '#f8fafc',
    secondaryColor: '#fbbf24',
    glowColor: 'rgba(255, 255, 255, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(248,250,252,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'pure_platinum_divine',
    eyeStyle: 'divine_omniscience_white',
    foreheadMark: 'heavenly_law_eye',
    ribbonStyle: 'golden_decree_scrolls',
    coreStyle: 'celestial_order_lattice',
    poem: 'Thiên đạo chí tôn, vạn linh thần phục.',
    desc: 'Đạo Anh đại diện cho chính bản nguyên ý chí của Thiên Đạo, thanh khiết vô tà, áp chế mọi tà ma quỷ quái trong cõi trần.',
    skillName: 'Thiên Quy Chế Tài Lệnh',
    skillDesc: 'Ban bố thiên quy, lập tức triệt tiêu toàn bộ hiệu ứng bất lợi đang chịu.',
    tribulationForm: 'Thái Thượng Vô Vi Thiên Đạo Thể',
  },
  {
    id: 'da_nguyen_gioi_hon_co',
    sourceType: 'lamp',
    sourceId: 'nguyen_gioi_hon_co',
    name: 'Nguyên Giới Hỗn Cổ Đạo Anh',
    title: 'Hồng Hoang Đại Địa Thần Vương',
    category: 'tao_hoa',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/nguyen_gioi_hon_co.png',
      '/images/dao_anh/nguyen_gioi_hon_co_k2.png',
      '/images/dao_anh/nguyen_gioi_hon_co_k3.png',
      '/images/dao_anh/nguyen_gioi_hon_co_k4.png',
      '/images/dao_anh/nguyen_gioi_hon_co_k5.png',
    ],
image: '/images/dao_anh/nguyen_gioi_hon_co.png',
    primaryColor: '#d97706',
    secondaryColor: '#10b981',
    glowColor: 'rgba(217, 119, 6, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(217,119,6,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'ancient_amber_bronze',
    eyeStyle: 'earth_primordial_amber',
    foreheadMark: 'ancient_world_runes',
    ribbonStyle: 'earth_vitality_currents',
    coreStyle: 'primordial_earth_core',
    poem: 'Hỗn cổ nguyên giới, vạn kiếp bất diệt.',
    desc: 'Đạo Anh mang khí tức trầm tích ngàn vạn dặm đất mẹ thời hỗn cổ, nền móng vững chắc tựa thái sơn bất khả lay chuyển.',
    skillName: 'Đại Địa Bản Nguyên Gia Trì',
    skillDesc: 'Tăng 100% Máu và Phòng Ngự của bản thân, không thể bị đẩy lùi hay rơi cảnh giới.',
    tribulationForm: 'Hỗn Cổ Hồng Hoang Bất Diệt Khu',
  },
  {
    id: 'da_cam_ky_cuc_dao',
    sourceType: 'lamp',
    sourceId: 'cam_ky_cuc_dao',
    name: 'Cấm Kỵ Cực Đạo Đạo Anh',
    title: 'Phá Diệt Thiên Quy Ma Thần',
    category: 'ma_dao',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/cam_ky_cuc_dao.png',
      '/images/dao_anh/cam_ky_cuc_dao_k2.png',
      '/images/dao_anh/cam_ky_cuc_dao_k3.png',
      '/images/dao_anh/cam_ky_cuc_dao_k4.png',
      '/images/dao_anh/cam_ky_cuc_dao_k5.png',
    ],
image: '/images/dao_anh/cam_ky_cuc_dao.png',
    primaryColor: '#ef4444',
    secondaryColor: '#0f172a',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(239,68,68,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'berserk_crimson_black',
    eyeStyle: 'demonic_rage_crimson',
    foreheadMark: 'forbidden_extreme_sigil',
    ribbonStyle: 'blood_thunder_fury',
    coreStyle: 'forbidden_singularity_core',
    poem: 'Cực đạo cấm kỵ, duy ngã độc tôn.',
    desc: 'Đạo Anh phá vỡ mọi cấm kỵ thiên đạo, sở hữu sức mạnh hủy diệt cực đoan, sẵn sàng thiêu đốt sinh mệnh để chém giết thần phật.',
    skillName: 'Cực Đạo Phá Diệt Quyết',
    skillDesc: 'Tăng 200% Sức Tấn Công trong 10 giây cuồng bạo khi bước vào ngưỡng sinh tử.',
    tribulationForm: 'Cấm Kỵ Ma Hoàng Bất Hoại Thân',
  },
  {
    id: 'da_dao_tam_chung_ma',
    sourceType: 'lamp',
    sourceId: 'dao_tam_chung_ma',
    name: 'Đạo Tâm Chủng Ma Đạo Anh',
    title: 'Tiên Ma Song Tu Chí Tôn',
    category: 'ma_dao',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/dao_tam_chung_ma.png',
      '/images/dao_anh/dao_tam_chung_ma_k2.png',
      '/images/dao_anh/dao_tam_chung_ma_k3.png',
      '/images/dao_anh/dao_tam_chung_ma_k4.png',
      '/images/dao_anh/dao_tam_chung_ma_k5.png',
    ],
image: '/images/dao_anh/dao_tam_chung_ma.png',
    primaryColor: '#a855f7',
    secondaryColor: '#facc15',
    glowColor: 'rgba(168, 85, 247, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(168,85,247,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'half_immortal_half_demon',
    eyeStyle: 'heterochromia_gold_red',
    foreheadMark: 'immortal_demon_seed',
    ribbonStyle: 'light_and_dark_twins',
    coreStyle: 'demon_seed_golden_lotus',
    poem: 'Đạo tâm chủng ma, siêu việt luân hồi.',
    desc: 'Đạo Anh là sự kết hợp cực hạn giữa Tiên Đạo thanh tịnh và Ma Đạo cuồng dã, tạo nên thực thể song cực vô địch thiên hạ.',
    skillName: 'Tiên Ma Đồng Thể Nghịch Chuyển',
    skillDesc: 'Chuyển hóa 50% sát thương nhận vào thành năng lượng Tiên Ma bùng nổ phản kích.',
    tribulationForm: 'Tiên Ma Tối Cao Vô Thượng Thân',
  },
  {
    id: 'da_tan_tien_phe_than',
    sourceType: 'lamp',
    sourceId: 'tan_tien_phe_than',
    name: 'Tàn Tiên Phệ Thần Đạo Anh',
    title: 'Thôn Hồn Đoạt Phách Tiên Linh',
    category: 'ma_dao',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/tan_tien_phe_than.png',
      '/images/dao_anh/tan_tien_phe_than_k2.png',
      '/images/dao_anh/tan_tien_phe_than_k3.png',
      '/images/dao_anh/tan_tien_phe_than_k4.png',
      '/images/dao_anh/tan_tien_phe_than_k5.png',
    ],
image: '/images/dao_anh/tan_tien_phe_than.png',
    primaryColor: '#06b6d4',
    secondaryColor: '#9333ea',
    glowColor: 'rgba(6, 182, 212, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(6,182,212,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'phantom_cyan_violet',
    eyeStyle: 'soul_consuming_cyan',
    foreheadMark: 'broken_immortal_seal',
    ribbonStyle: 'ghostly_soul_wisps',
    coreStyle: 'devouring_lamp_flame',
    poem: 'Tàn tiên vẫn lạc, phệ thần đoạt phách.',
    desc: 'Đạo Anh hình thành từ tàn niệm bất khuất của tiên nhân thượng cổ, chuyên thôn phệ thần phách của kẻ địch bồi bổ chân nguyên.',
    skillName: 'Phệ Thần Hóa Khí Thuật',
    skillDesc: 'Hút 30% chân khí mục tiêu mỗi khi gây sát thương, hồi phục ngay cho bản thể.',
    tribulationForm: 'Tàn Tiên Phục Sinh Chân Thần Thể',
  },

  // 24 VẬT TRẤN ÁP THẦN PHẨM
  {
    id: 'da_tao_hoa_ngoc_diep',
    sourceType: 'artifact',
    sourceId: 'tao_hoa_ngoc_diep',
    name: 'Tạo Hóa Ngọc Điệp Đạo Anh',
    title: 'Đạo Tổ Ba Ngàn Đại Đạo',
    category: 'tao_hoa',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/tao_hoa_ngoc_diep.png',
      '/images/dao_anh/tao_hoa_ngoc_diep_k2.png',
      '/images/dao_anh/tao_hoa_ngoc_diep_k3.png',
      '/images/dao_anh/tao_hoa_ngoc_diep_k4.png',
      '/images/dao_anh/tao_hoa_ngoc_diep_k5.png',
    ],
image: '/images/dao_anh/tao_hoa_ngoc_diep.png',
    primaryColor: '#34d399',
    secondaryColor: '#67e8f9',
    glowColor: 'rgba(52, 211, 153, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(52,211,153,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'jade_butterfly_crystal',
    eyeStyle: 'emerald_dao_glance',
    foreheadMark: 'tao_hoa_jade_butterfly',
    ribbonStyle: 'bamboo_scroll_inscriptions',
    coreStyle: 'three_thousand_dao_disc',
    poem: 'Tạo hóa ngọc điệp, thông hiểu vạn đạo.',
    desc: 'Đạo Anh trấn áp bằng mảnh vỡ Tạo Hóa Ngọc Điệp của Đạo Tổ, lĩnh ngộ 3000 đại đạo, giải trừ mọi bế tắc tu luyện.',
    skillName: 'Ba Ngàn Đại Đạo Thông Triệt',
    skillDesc: 'Tăng 100% Tốc Độ Lĩnh Ngộ Công Pháp, giảm 50% tiêu hao linh thạch & tiên tinh.',
    tribulationForm: 'Tạo Hóa Bích Điệp Tiên Hoàng Thể',
  },
  {
    id: 'da_kim_o_luyen_van_linh',
    sourceType: 'artifact',
    sourceId: 'kim_o_luyen_van_linh',
    name: 'Kim Ô Luyện Linh Đạo Anh',
    title: 'Thái Dương Kim Ô Thần Quân',
    category: 'thai_duong',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/kim_o_luyen_van_linh.png',
      '/images/dao_anh/kim_o_luyen_van_linh_k2.png',
      '/images/dao_anh/kim_o_luyen_van_linh_k3.png',
      '/images/dao_anh/kim_o_luyen_van_linh_k4.png',
      '/images/dao_anh/kim_o_luyen_van_linh_k5.png',
    ],
image: '/images/dao_anh/kim_o_luyen_van_linh.png',
    primaryColor: '#ea580c',
    secondaryColor: '#fde047',
    glowColor: 'rgba(234, 88, 12, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(234,88,12,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'solar_plasma_crimson_gold',
    eyeStyle: 'blazing_fire_sun_eyes',
    foreheadMark: 'three_legged_crow_seal',
    ribbonStyle: 'solar_flare_wings',
    coreStyle: 'sun_core_furnace',
    poem: 'Kim ô xuất thế, vạn linh quy phục.',
    desc: 'Đạo Anh ngưng tụ chân hỏa của Thần Điểu Kim Ô, thiêu rụi mọi chướng khí độc hại và luyện hóa linh khí thiên địa thành thuần dương.',
    skillName: 'Thái Dương Chân Hỏa Luyện Vạn Vật',
    skillDesc: 'Thiêu đốt kẻ địch gây sát thương chuẩn 5% máu mỗi giây không thể dập tắt.',
    tribulationForm: 'Kim Ô Thuần Dương Thánh Thể',
  },
  {
    id: 'da_nguyen_thuy_thai_so_ma_kinh',
    sourceType: 'artifact',
    sourceId: 'nguyen_thuy_thai_so_ma_kinh',
    name: 'Thái Sơ Ma Kinh Đạo Anh',
    title: 'Cổ Điển Sơ Khai Ma Hoàng',
    category: 'ma_dao',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/nguyen_thuy_thai_so_ma_kinh.png',
      '/images/dao_anh/nguyen_thuy_thai_so_ma_kinh_k2.png',
      '/images/dao_anh/nguyen_thuy_thai_so_ma_kinh_k3.png',
      '/images/dao_anh/nguyen_thuy_thai_so_ma_kinh_k4.png',
      '/images/dao_anh/nguyen_thuy_thai_so_ma_kinh_k5.png',
    ],
image: '/images/dao_anh/nguyen_thuy_thai_so_ma_kinh.png',
    primaryColor: '#7e22ce',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(126, 34, 206, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(126,34,206,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'runic_black_parchment',
    eyeStyle: 'ancient_crimson_slits',
    foreheadMark: 'primordial_script_seal',
    ribbonStyle: 'flying_black_scriptures',
    coreStyle: 'demon_scripture_tome',
    poem: 'Thái sơ vô cực, duy ngã độc tôn.',
    desc: 'Đạo Anh hóa thân từ bộ cổ kinh ma đạo sinh ra trước thiên địa, thân thể khắc chìm vô số ma văn sát phạt viễn cổ.',
    skillName: 'Thái Sơ Ma Chữ Trấn Sát',
    skillDesc: 'Phong tỏa 100% thần thông của đối thủ trong 5 giây khi giao chiến.',
    tribulationForm: 'Thái Sơ Ma Điển Bất Diệt Thân',
  },
  {
    id: 'da_dao_menh_thien_ma_cong',
    sourceType: 'artifact',
    sourceId: 'dao_menh_thien_ma_cong',
    name: 'Đoạt Mệnh Thiên Ma Đạo Anh',
    title: 'Đoạt Mệnh Càn Khôn Ma Đế',
    category: 'ma_dao',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/dao_menh_thien_ma_cong.png',
      '/images/dao_anh/dao_menh_thien_ma_cong_k2.png',
      '/images/dao_anh/dao_menh_thien_ma_cong_k3.png',
      '/images/dao_anh/dao_menh_thien_ma_cong_k4.png',
      '/images/dao_anh/dao_menh_thien_ma_cong_k5.png',
    ],
image: '/images/dao_anh/dao_menh_thien_ma_cong.png',
    primaryColor: '#475569',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(71,85,105,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'shadow_blood_phantom',
    eyeStyle: 'blood_vessel_demon_eyes',
    foreheadMark: 'life_stealing_glyph',
    ribbonStyle: 'shadow_tendrils_stream',
    coreStyle: 'life_reversal_matrix',
    poem: 'Đạo mệnh thiên ma, nghịch thiên cải mệnh.',
    desc: 'Đạo Anh cướp đoạt số mệnh trời đất của Thiên Ma Vực Ngoại, có thể nghịch chuyển tử cục thành sinh lộ.',
    skillName: 'Đoạt Mệnh Cải Vận Đại Pháp',
    skillDesc: 'Chuyển toàn bộ sát thương chí mạng thành lượng hồi phục sinh mệnh tương đương.',
    tribulationForm: 'Thiên Ma Nghịch Mệnh Vô Thượng Khu',
  },
  {
    id: 'da_ngu_hanh_dai_dong_thien',
    sourceType: 'artifact',
    sourceId: 'ngu_hanh_dai_dong_thien',
    name: 'Ngũ Hành Động Thiên Đạo Anh',
    title: 'Ngũ Hành Tương Sinh Chi Chủ',
    category: 'tao_hoa',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/ngu_hanh_dai_dong_thien.png',
      '/images/dao_anh/ngu_hanh_dai_dong_thien_k2.png',
      '/images/dao_anh/ngu_hanh_dai_dong_thien_k3.png',
      '/images/dao_anh/ngu_hanh_dai_dong_thien_k4.png',
      '/images/dao_anh/ngu_hanh_dai_dong_thien_k5.png',
    ],
image: '/images/dao_anh/ngu_hanh_dai_dong_thien.png',
    primaryColor: '#10b981',
    secondaryColor: '#3b82f6',
    glowColor: 'rgba(16, 185, 129, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(16,185,129,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'five_elements_pentagram',
    eyeStyle: 'pentachrome_elemental_eyes',
    foreheadMark: 'five_elements_ring',
    ribbonStyle: 'five_colored_spirit_rivers',
    coreStyle: 'five_elements_cave_haven',
    poem: 'Ngũ hành tương sinh, động thiên bất hoại.',
    desc: 'Đạo Anh ngưng kết từ không gian Ngũ Hành Đại Động Thiên viên mãn, tạo thế giới độc lập vững chắc bên trong đan điền.',
    skillName: 'Ngũ Sắc Thần Quang Tuyệt Kỹ',
    skillDesc: 'Quét tan và thu nạp mọi loại pháp bảo binh khí thuộc ngũ hành của đối phương.',
    tribulationForm: 'Ngũ Hành Hỗn Nguyên Đại Động Thể',
  },
  {
    id: 'da_mac_sat_tien_phach',
    sourceType: 'artifact',
    sourceId: 'mac_sat_tien_phach',
    name: 'Mặc Sát Tiên Phách Đạo Anh',
    title: 'Hủy Diệt Cực Hạn · Hắc Mặc Sát Diễm',
    category: 'ma_dao',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/mac_sat_tien_phach.png',
      '/images/dao_anh/mac_sat_tien_phach_k2.png',
      '/images/dao_anh/mac_sat_tien_phach_k3.png',
      '/images/dao_anh/mac_sat_tien_phach_k4.png',
      '/images/dao_anh/mac_sat_tien_phach_k5.png',
    ],
image: '/images/dao_anh/mac_sat_tien_phach.png',
    primaryColor: '#09090b',
    secondaryColor: '#3f3f46',
    glowColor: 'rgba(24, 24, 27, 0.95)',
    bgGradient: 'radial-gradient(circle, rgba(24,24,27,0.4) 0%, rgba(2,6,23,0.95) 100%)',
    bodyStyle: 'pitch_black_ink_flame_crystal',
    eyeStyle: 'void_black_fire_eyes',
    foreheadMark: 'ink_flame_destruction_crest',
    ribbonStyle: 'pure_black_ink_flame_wisps',
    coreStyle: 'extreme_destructive_dark_fire_core',
    poem: 'Mặc sát chân diễm, tịch diệt vạn linh.',
    desc: 'Đạo Anh ngưng kết từ Mặc Sát Tiên Phách — một loại lực lượng mang tính hủy diệt cực hạn nhưng hiển hiện dưới dạng ngọn lửa đen tuyền như mực. Bất kỳ pháp bảo, sinh mệnh hay cấm chế nào chạm phải ngọn lửa này đều bị ăn mòn và xóa sổ hoàn toàn khỏi tam giới.',
    skillName: 'Mặc Diễm Tịch Diệt Chân Hỏa',
    skillDesc: 'Phóng xuất ngọn lửa đen như mực thiêu rụi và xóa sổ 100% khiên chắn, ăn mòn vĩnh viễn sinh mệnh của kẻ địch.',
    tribulationForm: 'Mặc Diễm Hủy Diệt Tiên Phách Thể',
  },
  {
    id: 'da_huyen_hoang_diet_the_bien',
    sourceType: 'artifact',
    sourceId: 'huyen_hoang_diet_the_bien',
    name: 'Huyền Hoàng Diệt Thế Đạo Anh',
    title: 'Huyền Hoàng Khí Trọng Tinh Cầu',
    category: 'than_the',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/huyen_hoang_diet_the_bien.png',
      '/images/dao_anh/huyen_hoang_diet_the_bien_k2.png',
      '/images/dao_anh/huyen_hoang_diet_the_bien_k3.png',
      '/images/dao_anh/huyen_hoang_diet_the_bien_k4.png',
      '/images/dao_anh/huyen_hoang_diet_the_bien_k5.png',
    ],
image: '/images/dao_anh/huyen_hoang_diet_the_bien.png',
    primaryColor: '#b45309',
    secondaryColor: '#f59e0b',
    glowColor: 'rgba(180, 83, 9, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(180,83,9,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'heavy_huyen_hoang_earth',
    eyeStyle: 'heavy_planet_core_eyes',
    foreheadMark: 'huyen_hoang_mountain_mark',
    ribbonStyle: 'cosmic_dust_rings',
    coreStyle: 'planet_dense_core',
    poem: 'Huyền hoàng biến ảo, diệt thế trùng sinh.',
    desc: 'Đạo Anh dung hợp khí Huyền Hoàng dày nặng ngàn vạn trượng, một cử động mang theo uy lực nghiền nát tinh cầu.',
    skillName: 'Huyền Hoàng Vạn Quân Áp Trận',
    skillDesc: 'Tăng 120% Sức Nặng Uy Áp, làm chậm 80% tốc độ hành động của toàn bộ đối thủ.',
    tribulationForm: 'Huyền Hoàng Bất Toái Thần Vương Thể',
  },
  {
    id: 'da_am_duong_hon_don_nguyen_can',
    sourceType: 'artifact',
    sourceId: 'am_duong_hon_don_nguyen_can',
    name: 'Âm Dương Hỗn Độn Đạo Anh',
    title: 'Thái Cực Khai Thiên Hỗn Độn Thần Tôn',
    category: 'hon_don',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/am_duong_hon_don_nguyen_can.png',
      '/images/dao_anh/am_duong_hon_don_nguyen_can_k2.png',
      '/images/dao_anh/am_duong_hon_don_nguyen_can_k3.png',
      '/images/dao_anh/am_duong_hon_don_nguyen_can_k4.png',
      '/images/dao_anh/am_duong_hon_don_nguyen_can_k5.png',
    ],
image: '/images/dao_anh/am_duong_hon_don_nguyen_can.png',
    primaryColor: '#38bdf8',
    secondaryColor: '#f8fafc',
    glowColor: 'rgba(56, 189, 248, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(56,189,248,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'chaos_yin_yang_marble',
    eyeStyle: 'yin_yang_taiji_pupils',
    foreheadMark: 'bagua_taiji_primordial_crest',
    ribbonStyle: 'yin_yang_flowing_currents',
    coreStyle: 'taiji_chaos_origin_core',
    poem: 'Âm dương tương sinh, hỗn độn vô cực.',
    desc: 'Đạo Anh ngưng tụ từ hai khí Âm Dương thuở sơ khai, chưởng khống quy luật sinh diệt của càn khôn, chuyển hóa vạn vật về vô cực.',
    skillName: 'Âm Dương Hỗn Độn Nghịch Chuyển',
    skillDesc: 'Hấp thụ 50% toàn bộ sát thương chuyển hóa thành Chân Khí hộ thể, tăng 80% Sát Thương Tuyệt Đối thuộc tính Âm Dương Hỗn Độn.',
    tribulationForm: 'Âm Dương Hỗn Độn Vô Cực Thần Thân',
  },
  {
    id: 'da_luc_dao_luan_hoi_tien_can',
    sourceType: 'artifact',
    sourceId: 'luc_dao_luan_hoi_tien_can',
    name: 'Luân Hồi Tiên Căn Đạo Anh',
    title: 'Vạn Kiếp Bất Diệt Tiên Linh',
    category: 'luan_hoi',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/luc_dao_luan_hoi_tien_can.png',
      '/images/dao_anh/luc_dao_luan_hoi_tien_can_k2.png',
      '/images/dao_anh/luc_dao_luan_hoi_tien_can_k3.png',
      '/images/dao_anh/luc_dao_luan_hoi_tien_can_k4.png',
      '/images/dao_anh/luc_dao_luan_hoi_tien_can_k5.png',
    ],
image: '/images/dao_anh/luc_dao_luan_hoi_tien_can.png',
    primaryColor: '#8b5cf6',
    secondaryColor: '#38bdf8',
    glowColor: 'rgba(139, 92, 246, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(139,92,246,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'reincarnation_lotus_glass',
    eyeStyle: 'six_paths_mystic_gaze',
    foreheadMark: 'six_paths_lotus_seal',
    ribbonStyle: 'reincarnation_petals_flow',
    coreStyle: 'six_realms_immortal_sprout',
    poem: 'Lục đạo tiên căn, vạn kiếp bất diệt.',
    desc: 'Đạo Anh nắm giữ bí mật sinh tử của sáu cõi, giúp tu sĩ vĩnh viễn không bao giờ bị rơi rụng cảnh giới hay thụt lùi tu vi.',
    skillName: 'Bất Đọa Luân Hồi Quyết',
    skillDesc: 'Khóa chặt cảnh giới tu vi, tuyệt đối không bị suy giảm exp do bất kỳ nguyên nhân nào.',
    tribulationForm: 'Lục Đạo Tiên Căn Vĩnh Sinh Thân',
  },
  {
    id: 'da_tam_sinh_luan_hoi_an',
    sourceType: 'artifact',
    sourceId: 'tam_sinh_luan_hoi_an',
    name: 'Tam Sinh Luân Hồi Đạo Anh',
    title: 'Tam Thế Nhân Quả Thần Tôn',
    category: 'luan_hoi',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/tam_sinh_luan_hoi_an.png',
      '/images/dao_anh/tam_sinh_luan_hoi_an_k2.png',
      '/images/dao_anh/tam_sinh_luan_hoi_an_k3.png',
      '/images/dao_anh/tam_sinh_luan_hoi_an_k4.png',
      '/images/dao_anh/tam_sinh_luan_hoi_an_k5.png',
    ],
image: '/images/dao_anh/tam_sinh_luan_hoi_an.png',
    primaryColor: '#c084fc',
    secondaryColor: '#fde047',
    glowColor: 'rgba(192, 132, 252, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(192,132,252,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'tri_life_golden_amethyst',
    eyeStyle: 'three_lives_clairvoyance',
    foreheadMark: 'three_lifetimes_trident',
    ribbonStyle: 'past_present_future_ribbons',
    coreStyle: 'tri_temporal_seal_core',
    poem: 'Tam sinh ấn tích, định đoạn tiền trần.',
    desc: 'Đạo Anh kết tinh từ nhân quả ba đời tiền kiếp - hiện thế - tương lai, định đoạn số mệnh của kẻ thù chỉ bằng một niệm.',
    skillName: 'Tam Sinh Tam Thế Phong Ấn',
    skillDesc: 'Phong tỏa hoàn toàn quá khứ, hiện tại và tương lai của đối thủ, giảm 70% sát thương nhận vào.',
    tribulationForm: 'Tam Sinh Viên Mãn Thần Hoàng Thể',
  },
  {
    id: 'da_tran_nguc_minh_vuong_the',
    sourceType: 'artifact',
    sourceId: 'tran_nguc_minh_vuong_the',
    name: 'Minh Vương Trấn Ngục Đạo Anh',
    title: 'Cửu U Trấn Ngục Bất Hoại Thần',
    category: 'than_the',
    tier: 'than_pham',    evolutionImages: [
      '/images/dao_anh/tran_nguc_minh_vuong_the.png',
      '/images/dao_anh/tran_nguc_minh_vuong_the_k2.png',
      '/images/dao_anh/tran_nguc_minh_vuong_the_k3.png',
      '/images/dao_anh/tran_nguc_minh_vuong_the_k4.png',
      '/images/dao_anh/tran_nguc_minh_vuong_the_k5.png',
    ],
image: '/images/dao_anh/tran_nguc_minh_vuong_the.png',
    primaryColor: '#1e293b',
    secondaryColor: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(30,41,59,0.4) 0%, rgba(2,6,23,0.95) 100%)',
    bodyStyle: 'hell_iron_black_jade',
    eyeStyle: 'hellfire_crimson_glow',
    foreheadMark: 'prison_suppressing_talisman',
    ribbonStyle: 'hell_chains_spectral_fire',
    coreStyle: 'nine_hells_furnace_core',
    poem: 'Minh vương trấn ngục, vạn ma phủ phục.',
    desc: 'Đạo Anh đúc từ thể chất thần thoại trấn áp vạn ngục u minh, thể phách kiên cố bất hoại trước lôi kiếp tam tai cửu nạn.',
    skillName: 'Minh Vương Kim Cương Hộ Thân',
    skillDesc: 'Tăng 150% Giáp và Kháng Phép, phản lại 30% sát thương nhận vào cho kẻ tấn công.',
    tribulationForm: 'Trấn Ngục Kim Thân Thần Ma Thể',
  },
  {
    id: 'da_thai_so_than_vuong_the',
    sourceType: 'artifact',
    sourceId: 'thai_so_than_vuong_the',
    name: 'Thái Sơ Thần Vương Đạo Anh',
    title: 'Mười Phương Tinh Không Thần Vương',
    category: 'than_the',
    tier: 'than_pham',
    image: '/images/dao_anh/thai_so_than_vuong_the.png',
    primaryColor: '#fbbf24',
    secondaryColor: '#60a5fa',
    glowColor: 'rgba(251, 191, 36, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(251,191,36,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'divine_king_radiant_gold',
    eyeStyle: 'starry_sovereign_irises',
    foreheadMark: 'divine_king_diadem',
    ribbonStyle: 'celestial_court_drapes',
    coreStyle: 'ten_directions_stellar_core',
    poem: 'Thái sơ thần vương, ngạo thị chư thiên.',
    desc: 'Đạo Anh mang thần thể tối thượng của Thần Vương thuở sơ khai, mỗi bước đi chấn động mười phương tinh không thiên địa.',
    skillName: 'Thần Vương Tịnh Thổ Dị Tượng',
    skillDesc: 'Triệu hoán Thần Vương Tịnh Thổ, tăng 60% toàn bộ chỉ số cho tất cả Đạo Anh đồng hành.',
    tribulationForm: 'Thái Sơ Thần Vương Đại Đế Thân',
  },
  {
    id: 'da_tien_thien_thanh_the_dao_thai',
    sourceType: 'artifact',
    sourceId: 'tien_thien_thanh_the_dao_thai',
    name: 'Thánh Thể Đạo Thai Đạo Anh',
    title: 'Vạn Cổ Vô Địch Thể Chất',
    category: 'than_the',
    tier: 'than_pham',
    image: '/images/dao_anh/tien_thien_thanh_the_dao_thai.png',
    primaryColor: '#fde047',
    secondaryColor: '#a855f7',
    glowColor: 'rgba(253, 224, 71, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(253,224,71,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'sacred_body_dao_fetus',
    eyeStyle: 'golden_purple_sacred_eyes',
    foreheadMark: 'sacred_body_dao_thai_crest',
    ribbonStyle: 'sacred_golden_lotus_rain',
    coreStyle: 'innate_sacred_thai_embryo',
    poem: 'Thánh thể đạo thai, vạn cổ vô song.',
    desc: 'Sự dung hợp hoàn mỹ nhất vạn cổ giữa Hoang Cổ Thánh Thể và Tiên Thiên Đạo Thai, thể chất xưng tôn bất khả chiến bại.',
    skillName: 'Tiên Thiên Thánh Thể Dị Tượng',
    skillDesc: 'Miễn nhiễm 100% hiệu ứng khống chế, bộc phát 100% bạo kích trong 10 giây đầu trận.',
    tribulationForm: 'Vô Địch Vạn Cổ Thánh Thai Thần Thể',
  },
  {
    id: 'da_hon_don_diet_the_loi_tri',
    sourceType: 'artifact',
    sourceId: 'hon_don_diet_the_loi_tri',
    name: 'Diệt Thế Lôi Trì Đạo Anh',
    title: 'Hỗn Độn Lôi Trì Chưởng Quản',
    category: 'loi_dinh',
    tier: 'than_pham',
    image: '/images/dao_anh/hon_don_diet_the_loi_tri.png',
    primaryColor: '#38bdf8',
    secondaryColor: '#facc15',
    glowColor: 'rgba(56, 189, 248, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(56,189,248,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'chaos_thunder_pool_liquid',
    eyeStyle: 'electric_violet_thunderbolt',
    foreheadMark: 'thunder_pool_trident',
    ribbonStyle: 'surging_lightning_liquid',
    coreStyle: 'doomsday_thunder_cauldron',
    poem: 'Hỗn độn lôi trì, thối luyện thần khu.',
    desc: 'Đạo Anh ngâm mình trong bể sấm sét hỗn độn, hấp thu tinh hoa sấm sét để tôi luyện thể phách thành kim cương bất hoại.',
    skillName: 'Hỗn Độn Lôi Trì Tôi Thể',
    skillDesc: 'Mỗi lần trúng lôi kiếp sẽ chuyển hóa 50% sát thương lôi phạt thành EXP tu vi vĩnh viễn.',
    tribulationForm: 'Bất Hoại Lôi Thể Kim Cương Thần',
  },
  {
    id: 'da_khoi_nguyen_vu_tru_ban_nguyen',
    sourceType: 'artifact',
    sourceId: 'khoi_nguyen_vu_tru_ban_nguyen',
    name: 'Vũ Trụ Bản Nguyên Đạo Anh',
    title: 'Vũ Trụ Khởi Nguyên Tinh Hải',
    category: 'hon_don',
    tier: 'than_pham',
    image: '/images/dao_anh/khoi_nguyen_vu_tru_ban_nguyen.png',
    primaryColor: '#c084fc',
    secondaryColor: '#38bdf8',
    glowColor: 'rgba(192, 132, 252, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(192,132,252,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'universe_primordial_starfield',
    eyeStyle: 'galaxy_cluster_eyes',
    foreheadMark: 'universe_origin_singularity',
    ribbonStyle: 'nebula_gas_currents',
    coreStyle: 'universal_genesis_matrix',
    poem: 'Khởi nguyên bản nguyên, diễn sinh vạn giới.',
    desc: 'Đạo Anh chứa đựng khối năng lượng bản nguyên đầu tiên sinh ra vũ trụ, nâng đỡ vững chãi toàn bộ lầu các thiên cung.',
    skillName: 'Khởi Nguyên Thế Giới Lực',
    skillDesc: 'Tăng 70% Uy Lực của toàn bộ Thần Thông Công Pháp đang trang bị.',
    tribulationForm: 'Khởi Nguyên Vũ Trụ Đạo Tôn Thể',
  },
  {
    id: 'da_tha_hoa_tu_tai_dai_phap',
    sourceType: 'artifact',
    sourceId: 'tha_hoa_tu_tai_dai_phap',
    name: 'Tha Hóa Tự Tại Đạo Anh',
    title: 'Tha Hóa Vạn Cổ Chi Tôn',
    category: 'thoi_khong',
    tier: 'than_pham',
    image: '/images/dao_anh/tha_hoa_tu_tai_dai_phap.png',
    primaryColor: '#fde047',
    secondaryColor: '#ec4899',
    glowColor: 'rgba(253, 224, 71, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(253,224,71,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'avatar_multi_spectral_gold',
    eyeStyle: 'temporal_clone_shimmer',
    foreheadMark: 'tha_hoa_infinite_avatars',
    ribbonStyle: 'timeless_mirror_reflections',
    coreStyle: 'infinite_clones_nexus',
    poem: 'Tha hóa tự tại, tha hóa vạn cổ.',
    desc: 'Đại pháp cái thế hóa ra vô số phân thân chân thân trong dòng chảy vạn cổ thời không để bảo vệ đạo quả bất diệt.',
    skillName: 'Tha Hóa Vạn Cổ Phân Thân',
    skillDesc: 'Tạo ra 3 phân thân Đạo Anh chiến đấu tương đương 100% sức mạnh bản thể.',
    tribulationForm: 'Tha Hóa Tự Tại Vĩnh Kiếp Thần Thân',
  },
  {
    id: 'da_tieu_tuc_menh_thuat',
    sourceType: 'artifact',
    sourceId: 'tieu_tuc_menh_thuat',
    name: 'Tiểu Túc Mệnh Đạo Anh',
    title: 'Thiêu Đốt Thọ Nguyên Cải Mệnh',
    category: 'luan_hoi',
    tier: 'than_pham',
    image: '/images/dao_anh/tieu_tuc_menh_thuat.png',
    primaryColor: '#f43f5e',
    secondaryColor: '#e2e8f0',
    glowColor: 'rgba(244, 63, 94, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(244,63,94,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'destiny_chain_ruby',
    eyeStyle: 'burning_lifespan_flame',
    foreheadMark: 'broken_destiny_chains',
    ribbonStyle: 'iron_destiny_shackles',
    coreStyle: 'lifespan_burning_flame',
    poem: 'Túc mệnh sở hướng, vạn pháp quy phục.',
    desc: 'Đạo Anh triệu hoán lực lượng túc mệnh vĩ đại, cắt đứt mọi xiềng xích quy tắc để đạt được chiến lực vô địch trong sát na.',
    skillName: 'Túc Mệnh Đại Triệu Hoán',
    skillDesc: 'Thiêu đốt 50 Điểm Thiên Mệnh để tăng 300% Sát Thương Tuyệt Đối trong 15 giây.',
    tribulationForm: 'Nghịch Thiên Túc Mệnh Thần Hoàng Khu',
  },
  {
    id: 'da_con_bang_tien_phap',
    sourceType: 'artifact',
    sourceId: 'con_bang_tien_phap',
    name: 'Côn Bằng Tiên Pháp Đạo Anh',
    title: 'Thái Cổ Thập Hung · Côn Bằng',
    category: 'than_the',
    tier: 'than_pham',
    image: '/images/dao_anh/con_bang_tien_phap.png',
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    glowColor: 'rgba(2, 132, 199, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(2,132,199,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'kunpeng_dual_avian_aquatic',
    eyeStyle: 'kunpeng_piercing_amber',
    foreheadMark: 'kunpeng_wings_crest',
    ribbonStyle: 'ocean_wave_and_sky_wings',
    coreStyle: 'yin_yang_ocean_sky_core',
    poem: 'Côn bằng giương cánh, xé toạc cửu thiên.',
    desc: 'Đạo Anh chưởng khống cực hạn âm dương và tốc độ vô địch thiên hạ của Thập Hung Côn Bằng, vào nước là Côn, lên trời là Bằng.',
    skillName: 'Côn Bằng Cửu Thiên Bộ',
    skillDesc: 'Tăng 150% Tốc Độ Né Tránh và Di Chuyển, tạo sóng kình âm dương công phá toàn bộ trận đồ.',
    tribulationForm: 'Thái Cổ Côn Bằng Thần Điểu Thân',
  },
  {
    id: 'da_can_khon_luong_nghi_ho',
    sourceType: 'artifact',
    sourceId: 'can_khon_luong_nghi_ho',
    name: 'Càn Khôn Lưỡng Nghi Đạo Anh',
    title: 'Tiên Thiên Thần Hồ Ôn Đạo',
    category: 'tao_hoa',
    tier: 'than_pham',
    image: '/images/dao_anh/can_khon_luong_nghi_ho.png',
    primaryColor: '#10b981',
    secondaryColor: '#fbbf24',
    glowColor: 'rgba(16, 185, 129, 0.8)',
    bgGradient: 'radial-gradient(circle, rgba(16,185,129,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'gourd_jade_amber',
    eyeStyle: 'celestial_wine_twinkle',
    foreheadMark: 'yin_yang_gourd_crest',
    ribbonStyle: 'spiritual_nectar_vapors',
    coreStyle: 'nine_turn_elixir_spring',
    poem: 'Càn khôn lưỡng nghi, thâu tẫn càn khôn.',
    desc: 'Đạo Anh ôm trong tay hồ lô tiên thiên, thu nạp hai khí âm dương đất trời rồi chuyển hóa thành cửu chuyển linh dịch nuôi dưỡng Kim Đan.',
    skillName: 'Càn Khôn Luyện Đan Bí Quyết',
    skillDesc: 'Tự động ngưng tụ 1 viên Thần Cấp Linh Đan mỗi ngày giúp gia tăng 5,000 EXP tu vi.',
    tribulationForm: 'Càn Khôn Dưỡng Đạo Tiên Đồng Thể',
  },
  {
    id: 'da_cuu_kiep_loi_nguc_kiem_phap',
    sourceType: 'artifact',
    sourceId: 'cuu_kiep_loi_nguc_kiem_phap',
    name: 'Lôi Ngục Kiếm Pháp Đạo Anh',
    title: 'Chín Tầng Lôi Ngục Trảm Ma Kiếm',
    category: 'kiem_dao',
    tier: 'than_pham',
    image: '/images/dao_anh/cuu_kiep_loi_nguc_kiem_phap.png',
    primaryColor: '#6366f1',
    secondaryColor: '#facc15',
    glowColor: 'rgba(99, 102, 241, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(99,102,241,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'thunder_prison_blade_steel',
    eyeStyle: 'sword_thunder_sparkle',
    foreheadMark: 'nine_tribulations_sword',
    ribbonStyle: 'flying_thunder_swords',
    coreStyle: 'nine_tier_thunder_prison',
    poem: 'Cửu kiếp lôi ngục, kiếm trảm thần ma.',
    desc: 'Đạo Anh triệu hoán chín tầng ngục sấm sét, vung kiếm trảm diệt mọi sinh cơ và phong tỏa hoàn toàn không gian của kẻ địch.',
    skillName: 'Cửu Kiếp Lôi Ngục Kiếm Trận',
    skillDesc: 'Giam cầm toàn bộ kẻ địch trong kiếm trận lôi đình, giáng 9 đợt sát thương sấm sét liên hoàn.',
    tribulationForm: 'Cửu Kiếp Lôi Ngục Kiếm Tiên Thể',
  },
  {
    id: 'da_van_de_tran_ma_quyen',
    sourceType: 'artifact',
    sourceId: 'van_de_tran_ma_quyen',
    name: 'Vạn Đế Trấn Ma Đạo Anh',
    title: 'Vạn Vị Cổ Đế Hợp Nhất Quyền',
    category: 'than_the',
    tier: 'than_pham',
    image: '/images/dao_anh/van_de_tran_ma_quyen.png',
    primaryColor: '#f97316',
    secondaryColor: '#fbbf24',
    glowColor: 'rgba(249, 115, 22, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(249,115,22,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'ten_thousand_emperors_aura',
    eyeStyle: 'ancient_emperor_fury',
    foreheadMark: 'emperor_fist_sigil',
    ribbonStyle: 'emperor_battle_banners',
    coreStyle: 'sovereign_fist_dominion',
    poem: 'Vạn đế hợp lực, nhất quyền trấn ma.',
    desc: 'Đạo Anh mang quyền ý ngưng tụ của vạn vị cổ đế thượng cổ, một quyền vung ra khiến thiên băng địa liệt, ma thần tan biến.',
    skillName: 'Vạn Đế Quy Nhất Quyền',
    skillDesc: 'Tung đòn đấm mang uy lực gấp 500% sát thương cơ bản, phá tan mọi khiên phòng ngự.',
    tribulationForm: 'Vạn Đế Chí Tôn Hoàng Quyền Thân',
  },
  {
    id: 'da_nhat_khi_hoa_tam_thanh',
    sourceType: 'artifact',
    sourceId: 'nhat_khi_hoa_tam_thanh',
    name: 'Nhất Khí Tam Thanh Đạo Anh',
    title: 'Đạo Môn Chí Tôn Tam Đạo Thân',
    category: 'tao_hoa',
    tier: 'than_pham',
    image: '/images/dao_anh/nhat_khi_hoa_tam_thanh.png',
    primaryColor: '#22d3ee',
    secondaryColor: '#fde047',
    glowColor: 'rgba(34, 211, 238, 0.85)',
    bgGradient: 'radial-gradient(circle, rgba(34,211,238,0.2) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'tri_pure_daoist_crystal',
    eyeStyle: 'triple_dao_gaze',
    foreheadMark: 'three_pure_ones_trigram',
    ribbonStyle: 'three_colored_celestial_qi',
    coreStyle: 'pure_vital_energy_trinity',
    poem: 'Nhất khí hóa tam thanh, vạn cổ duy ngã tôn.',
    desc: 'Đạo Anh tu luyện thần thông tối cao Đạo Môn, một luồng chân khí phân hóa thành ba phân thân tương đương sức mạnh bản thể.',
    skillName: 'Nhất Khí Tam Thanh Diễn Hóa',
    skillDesc: 'Tăng gấp 3 lần số lượng hiệu ứng bị động từ các bảo vật trấn áp đang trang bị.',
    tribulationForm: 'Thái Thanh Ngọc Thanh Thượng Thanh Thể',
  },
  {
    id: 'da_vo_thuy_vo_chung_vo_vi_than',
    sourceType: 'artifact',
    sourceId: 'vo_thuy_vo_chung_vo_vi_than',
    name: 'Vô Thủy Vô Chung Đạo Anh',
    title: 'Vĩnh Hằng Bất Hủ Đạo Thể',
    category: 'than_the',
    tier: 'than_pham',
    image: '/images/dao_anh/vo_thuy_vo_chung_vo_vi_than.png',
    primaryColor: '#cbd5e1',
    secondaryColor: '#facc15',
    glowColor: 'rgba(203, 213, 225, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(203,213,225,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'timeless_ouroboros_platinum',
    eyeStyle: 'beginning_and_end_infinity',
    foreheadMark: 'ouroboros_infinity_ring',
    ribbonStyle: 'ouroboros_light_bands',
    coreStyle: 'infinite_spacetime_knot',
    poem: 'Vô thủy vô chung, vĩnh hằng bất diệt.',
    desc: 'Đạo Anh không có khởi đầu cũng không có kết thúc, đứng ngoài dòng chảy sinh diệt tam giới, miễn nhiễm mọi đòn sát phạt hủy diệt.',
    skillName: 'Vô Vi Vĩnh Hằng Giới',
    skillDesc: 'Vô hiệu hóa hoàn toàn 3 đòn tấn công chí mạng liên tiếp trong mỗi trận đại chiến.',
    tribulationForm: 'Vô Thủy Vô Chung Chí Tôn Đạo Thai',
  },
  {
    id: 'da_diet_the_loi_viem_dong',
    sourceType: 'artifact',
    sourceId: 'diet_the_loi_viem_dong',
    name: 'Lôi Viêm Đồng Đạo Anh',
    title: 'Diệt Thế Lôi Viêm Thần Nhãn',
    category: 'loi_dinh',
    tier: 'than_pham',
    image: '/images/dao_anh/diet_the_loi_viem_dong.png',
    primaryColor: '#ef4444',
    secondaryColor: '#60a5fa',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    bgGradient: 'radial-gradient(circle, rgba(239,68,68,0.25) 0%, rgba(15,23,42,0.95) 100%)',
    bodyStyle: 'thunder_flame_pupil_ruby',
    eyeStyle: 'thunder_fire_eye_pupils',
    foreheadMark: 'thunder_flame_third_eye',
    ribbonStyle: 'intertwined_thunder_and_fire',
    coreStyle: 'doomsday_blazing_core',
    poem: 'Lôi viêm đồng tử, chiếu rọi chư thiên.',
    desc: 'Đạo Anh sở hữu con mắt thần thoại ngưng tụ lôi đình và ngọn lửa diệt thế, một ánh nhìn thiêu rụi hư không và cấm chế tam giới.',
    skillName: 'Lôi Viêm Diệt Thế Thần Quang',
    skillDesc: 'Bắn tia thần quang phá hủy 100% khiên chắn và gây sát thương diện rộng thiêu đốt toàn cõi.',
    tribulationForm: 'Lôi Viêm Thần Đồng Bất Diệt Hoàng',
  },
];

/**
 * Tìm định nghĩa Đạo Anh tương ứng trong DAO_ANH_LIST
 */
export function findDaoAnhDefinition(da, state) {
  if (!da) return DAO_ANH_LIST[0];

  // 1. Check trực tiếp theo da.id nếu trùng
  if (da.id) {
    const directMatch = DAO_ANH_LIST.find(d => d.id === da.id || d.sourceId === da.id);
    if (directMatch) return directMatch;
  }

  // 2. Phân giải theo cung mệnh đăng hoặc vật trấn áp
  const pIdx = da.palaceIndex !== undefined ? da.palaceIndex : 0;
  const maxThienCung = state?.maxThienCung || 13;
  const lampList = state?.absorbedLamps || [];
  const lampCount = lampList.length;
  const selfPalacesTotal = Math.max(1, maxThienCung - lampCount);
  const isLampPalace = pIdx >= selfPalacesTotal;

  if (isLampPalace) {
    const lampIdx = pIdx - selfPalacesTotal;
    const lampId = lampList[lampIdx] || da.lampId;
    if (lampId) {
      const match = DAO_ANH_LIST.find(d => d.sourceType === 'lamp' && d.sourceId === lampId);
      if (match) return match;
    }
  } else {
    const anchor = state?.palaceAnchors?.[pIdx] || state?.palaceAnchors?.[selfPalacesTotal - 1 - pIdx];
    const artId = anchor?.id || da.artifactId;
    if (artId) {
      const match = DAO_ANH_LIST.find(d => d.sourceType === 'artifact' && d.sourceId === artId);
      if (match) return match;
    }
  }

  // 3. Fallback tìm kiếm theo tên
  const cleanName = (da.name || '').toLowerCase();
  const matchByName = DAO_ANH_LIST.find(d => 
    (d.name && cleanName.includes(d.name.toLowerCase().replace('đạo anh', '').trim())) ||
    (d.sourceId && cleanName.includes(d.sourceId.replace(/_/g, ' ')))
  );
  if (matchByName) return matchByName;

  return DAO_ANH_LIST[0];
}

const daoAnhModules = import.meta.glob('../assets/images/dao_anh/*.png', { eager: true, import: 'default' });
const bundledDaoAnh = {};

for (const [filepath, mod] of Object.entries(daoAnhModules)) {
  const filename = filepath.split(/[\/\\]/).pop().split('.')[0];
  bundledDaoAnh[filename] = mod;
}

export { getAssetUrl } from './assetHelper';

export function resolveDaoAnhImage(rawPathOrId) {
  if (!rawPathOrId) return '';
  if (rawPathOrId.startsWith('http') || rawPathOrId.startsWith('data:')) return rawPathOrId;
  const cleanKey = rawPathOrId.split(/[\/\\]/).pop().split('.')[0];
  return bundledDaoAnh[cleanKey] || rawPathOrId;
}

/**
 * Lấy URL hình ảnh Đạo Ảnh theo tầng Kiếp (Kiếp 1 -> Kiếp 5)
 * Sử dụng asset bundle của Vite cho tốc độ load tức thì 0ms.
 */
export function getDaoAnhEvolutionImage(daoAnhDef, currentKiep = 0) {
  if (!daoAnhDef) return '';
  const kiep = typeof currentKiep === 'number' ? currentKiep : 0;

  let chosenPath = daoAnhDef.image || '';
  if (Array.isArray(daoAnhDef.evolutionImages) && daoAnhDef.evolutionImages.length > 0) {
    const targetIndex = kiep <= 1 ? 0 : Math.min(daoAnhDef.evolutionImages.length - 1, kiep - 1);
    if (daoAnhDef.evolutionImages[targetIndex]) {
      chosenPath = daoAnhDef.evolutionImages[targetIndex];
    }
  }

  return resolveDaoAnhImage(chosenPath);
}

/** Preload all 5 Kiep evolution images of all Dao Anh into browser memory */
let _hasPreloadedDaoAnh = false;
export function preloadAllDaoAnhEvolutionImages() {
  if (typeof window === 'undefined' || _hasPreloadedDaoAnh) return;
  _hasPreloadedDaoAnh = true;

  const runPreload = () => {
    Object.values(bundledDaoAnh).forEach((imgUrl) => {
      if (imgUrl) {
        const img = new Image();
        img.src = imgUrl;
      }
    });
  };

  if ('requestIdleCallback' in window) {
    window.requestIdleCallback(runPreload, { timeout: 1500 });
  } else {
    setTimeout(runPreload, 50);
  }
}

/**
 * Danh sách ID các Đạo Ảnh có dáng nghiêng/xòe cần phóng to kích thước
 */
export const DAO_ANH_ENLARGED_IDS = new Set([
  'da_van_gioi_quy_nhat',
  'van_gioi_quy_nhat',
  'da_khoi_nguyen_vu_tru_ban_nguyen',
  'khoi_nguyen_vu_tru_ban_nguyen',
  'da_cam_ky_cuc_dao',
  'cam_ky_cuc_dao',
  'da_dao_tam_chung_ma',
  'dao_tam_chung_ma',
  'da_tan_tien_phe_than',
  'tan_tien_phe_than',
  'da_nguyen_thuy_thai_so_ma_kinh',
  'nguyen_thuy_thai_so_ma_kinh',
  'da_dao_menh_thien_ma_cong',
  'dao_menh_thien_ma_cong',
  'da_diet_the_loi_viem_dong',
  'diet_the_loi_viem_dong',
  'da_tuc_menh_nhan_qua',
  'tuc_menh_nhan_qua',
  'da_luc_dao_luan_hoi_tien_can',
  'luc_dao_luan_hoi_tien_can',
  'da_tam_sinh_luan_hoi_an',
  'tam_sinh_luan_hoi_an',
  'da_tieu_tuc_menh_thuat',
  'tieu_tuc_menh_thuat',
  'da_sang_the_ban_nguyen',
  'sang_the_ban_nguyen',
  'da_kim_o_luyen_van_linh',
  'kim_o_luyen_van_linh',
  'da_khoi_nguyen_thoi_khong',
  'khoi_nguyen_thoi_khong',
  'da_nguyen_gioi_hon_co',
  'nguyen_gioi_hon_co',
  'da_ngu_hanh_dai_dong_thien',
  'ngu_hanh_dai_dong_thien',
  'da_can_khon_luong_nghi_ho',
  'can_khon_luong_nghi_ho',
  'da_nhat_khi_hoa_tam_thanh',
  'nhat_khi_hoa_tam_thanh',
  'da_thai_co_than_long',
  'thai_co_than_long',
  'da_thien_dao_chi_ton',
  'thien_dao_chi_ton',
  'da_tran_nguc_minh_vuong_the',
  'tran_nguc_minh_vuong_the',
  'da_vo_thuy_vo_chung_vo_vi_than',
  'vo_thuy_vo_chung_vo_vi_than',
]);

/**
 * Lấy tỉ lệ phóng to (scale factor) của Đạo Ảnh
 */
export function getDaoAnhScale(daoAnhDef) {
  if (!daoAnhDef) return 1;
  if (typeof daoAnhDef.avatarScale === 'number') return daoAnhDef.avatarScale;
  const id = daoAnhDef.id || '';
  const sourceId = daoAnhDef.sourceId || '';
  if (DAO_ANH_ENLARGED_IDS.has(id) || DAO_ANH_ENLARGED_IDS.has(sourceId)) {
    return 1.32; // Tăng ~32% kích thước
  }
  return 1;
}

